### ISSUE TITLE
Exception Caught - java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by NavigatorBR** [Podbrushkin/Imker-hotfix#2]
Not sure how serious an issue this is, as _Imker-hotfix_ does seem to still be downloading files without issue, but after downloading, a window titled "Exception Caught" appears.

The window said to provide the following to report the bug:
> Version: v16.09.13

Stack trace:
```java
java.lang.UnsupportedClassVersionError: jakarta/xml/bind/annotation/adapters/HexBinaryAdapter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at app.ImkerBase.calcSHA1(ImkerBase.java:314)
	at app.ImkerBase.checksumLoop(ImkerBase.java:206)
	at app.ImkerGUI$5.doInBackground(ImkerGUI.java:410)
	at app.ImkerGUI$5.doInBackground(ImkerGUI.java:404)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```
I also attempted to solve this by following the tip to create and use the text file _ImkerRun.bat_ if there was an issue, but still encountered the issue.

**PS:** Thanks for finding a solution to getting this tool working again.

**Comment by Podbrushkin** [comment]
First line of stacktrace is informative. Class in jakarta.xml.bind.* package is compiled with more recent (11) version of java, than one you're trying to run it with(8). [versions table](https://javaalmanac.io/bytecode/versions/). 
I think this error will disappear, if you will update version of Java installed in your system.
Check what version of  Java is installed:  `Win+R -> cmd -> Enter -> java --version -> Enter`. Probably output will be like `java 8.****`. If so, you can try to update your java version to 11 or more recent. Probably it wouldn't hurt any other apps. If you wish to update java, say it, I will explain how.
But actually, problem is not on your side, because original Imker is built in Java 8, and you have Java 8, and it's me who changed javax.xml.bind.* to jakarta.xml.bind.*, probably I shouldn't have done it. I will revert it back but will not update jar executable yet, because issue is small, and new releases of jar will make it harder for other people to make sure I didn't add to this app anything malicious.

**Comment by Podbrushkin** [comment]
I've added new `imker.jar` to Releases (0.0.2), now it is compiled in java8 and should not have UnsupportedClassVersionError, should work fine in Java 8 as expected. Just download latest `Imker.jar` and use it instead of an old one.
